"""add ballots table

Revision ID: 402c136d769c
Revises: 42aa0eb71790
Create Date: 2026-07-31 16:51:01.359819

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "402c136d769c"
down_revision: str | Sequence[str] | None = "42aa0eb71790"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ballots",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("vote_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("option_id", sa.UUID(), nullable=False),
        sa.Column("cast_by_owner_id", sa.UUID(), nullable=False),
        sa.Column("cast_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("superseded_by_ballot_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["superseded_by_ballot_id"],
            ["ballots.id"],
            initially="DEFERRED",
            deferrable=True,
        ),
        sa.ForeignKeyConstraint(["vote_id"], ["votes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ballots_active_per_vote_unit",
        "ballots",
        ["vote_id", "unit_id"],
        unique=True,
        postgresql_where=sa.text("superseded_by_ballot_id IS NULL"),
    )
    op.create_index(
        op.f("ix_ballots_vote_id"), "ballots", ["vote_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_ballots_active_per_vote_unit",
        table_name="ballots",
        postgresql_where=sa.text("superseded_by_ballot_id IS NULL"),
    )
    op.drop_index(op.f("ix_ballots_vote_id"), table_name="ballots")
    op.drop_table("ballots")
    # ### end Alembic commands ###
