"""add unique constraint on accounts owner_id

Revision ID: d239d8a15d6b
Revises: 402c136d769c
Create Date: 2026-08-06 10:00:31.888038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd239d8a15d6b'
down_revision: Union[str, Sequence[str], None] = '402c136d769c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_accounts_owner_id', 'accounts', ['owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_accounts_owner_id', 'accounts', type_='unique')
    # ### end Alembic commands ###
